service:
  type: LoadBalancer
  ports:
    web:
      port: 80
      targetPort: 8081  # Non-privileged port
      nodePort: 30080
    websecure:
      port: 443
      targetPort: 8443  # Non-privileged port
      nodePort: 30443

additionalArguments:
  - "--entrypoints.web.address=:8081"      # Use non-privileged port
  - "--entrypoints.websecure.address=:8443" # Use non-privileged port
  - "--certificatesresolvers.letsresolver.acme.httpchallenge=true"
  - "--certificatesresolvers.letsresolver.acme.httpchallenge.entrypoint=web"
  - "--certificatesresolvers.letsresolver.acme.email=boitumelok.ngwenya@gmail.com"
  - "--certificatesresolvers.letsresolver.acme.storage=/data/acme.json"

extraVolumeMounts:
  - name: data
    mountPath: /data

extraVolumes:
  - name: data
    emptyDir: {}

podSecurityContext:
  fsGroup: 65532
  runAsUser: 65532
  runAsGroup: 65532
  runAsNonRoot: true

securityContext:
  runAsUser: 65532
  runAsGroup: 65532
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL